# Generated by Django 4.0.1 on 2022-03-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='food',
        ),
        migrations.AddField(
            model_name='foodstatic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.users'),
            preserve_default=False,
        ),
    ]
