# Generated by Django 4.0.1 on 2022-03-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_users_food_foodstatic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodstatic',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='food.users'),
        ),
    ]
