# Generated by Django 4.0.1 on 2022-03-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_userfood_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfood',
            name='food',
            field=models.ManyToManyField(blank=True, to='food.Food'),
        ),
    ]
