# Generated by Django 4.0.1 on 2022-03-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_foodstatic_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodstatic',
            name='user',
        ),
        migrations.CreateModel(
            name='FoodUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.foodstatic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.users')),
            ],
        ),
    ]
